pull request
khFinal05/final05_html pull request #6
Opened 2023-10-12 08:24 UTC by khFinal05

검토해주세요

2023-10-12 08:24 UTC, nangmangorani approved these changes
이게코드? ㅋ

2023-10-12 08:24 UTC, nangmangorani requested changes
이게코드? ㅋ

2023-10-12 08:24 UTC, YoonTarget requested changes
응 돌아가

2023-10-12 08:25 UTC, nangmangorani approved these changes
ㅋ

2023-10-12 08:25 UTC, YoonTarget approved these changes
이번만 봐줌

2023-10-12 08:26 UTC, merged

2023-10-13 08:40 UTC, nangmangorani commented
ㅋ

2023-10-17 08:40 UTC, YoonTarget commented
![콧수염감스트](https://github.com/khFinal05/final05_html/assets/126389803/5c0fbcc1-9b63-4410-9264-0b71b9023074)